# Generated by Django 2.2.16 on 2020-11-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storys.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(default=False, max_length=30)),
                ('image', models.ImageField(upload_to=storys.models.img_path)),
                ('image_ver', models.IntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storys.Story')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
