# Generated by Django 2.2.16 on 2020-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0002_bookstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstory',
            name='content0',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content4',
            field=models.ImageField(upload_to=''),
        ),
    ]
