# Generated by Django 2.2.16 on 2020-11-09 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0002_auto_20201104_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AddField(
            model_name='story',
            name='content0',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
