# Generated by Django 2.2.16 on 2020-11-16 04:22

from django.db import migrations, models
import storys.models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0003_auto_20201116_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstory',
            name='content0',
            field=models.ImageField(upload_to=storys.models.bimg_path),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content1',
            field=models.ImageField(upload_to=storys.models.bimg_path),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content2',
            field=models.ImageField(upload_to=storys.models.bimg_path),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content3',
            field=models.ImageField(upload_to=storys.models.bimg_path),
        ),
        migrations.AlterField(
            model_name='bookstory',
            name='content4',
            field=models.ImageField(upload_to=storys.models.bimg_path),
        ),
    ]
