# Generated by Django 2.2.16 on 2020-11-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bookcover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
