# Generated by Django 2.2.16 on 2020-11-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20201112_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storys.Story'),
        ),
    ]
