# Generated by Django 2.2.16 on 2020-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201115_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bookcover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
